all: guessFruit solveMeFirst fflush_ex
	
guessFruit: guessFruit.c
	gcc -o guessFruit.o guessFruit.c

solveMeFirst: solveMeFirst.c
	gcc -o solveMeFirst.o solveMeFirst.c

fflush_ex: fflush_ex.c
	gcc -o fflush_ex.o fflush_ex.c

clean:
	rm *.o
